### ISSUE TITLE
Move terminology page

### ISSUE THREAD

**Issue by rcannood** [viash-io/new_website#4]
I think it's a bit strange to put the Terminology page under "Help". Maybe it'd fit better in the guide?

Also, the Terminology link currently opens up a new window. I don't think this is desirable.

**Comment by BlackDragonBE** [comment]
@rcannood Agreed. It's a bit hidden at the moment. I'll move it to the bottom of the Guide for now.
As for opening in a new window that's a known (to me) issue. Only external links open in a new tab/window. However, because the domain is set up as viash.io, the system marks all links on github.io as external. This will be automatically fixed once we deploy the website.

**Comment by BlackDragonBE** [comment]
Solved in 48c10d8e3bf4a5d7f51edaf617296fc030a99c57
